export const ORDER_ITEM_CATALOG = {
  "samosa": { name: "Samosa", price: 8.95 },
  "sweet-sour-gobi": { name: "Sweet & Sour Gobi", price: 8.95 },
  "kachori-chaat": { name: "Kachori Chaat", price: 8.95 },
  "papri-chaat": { name: "Papri Chaat", price: 8.95 },
  "onion-bhajjias": { name: "Onion Bhajjias", price: 9.95 },
  "assorted-pakora": { name: "Assorted Pakora", price: 9.95 },
  "tandoori-mix-veg": { name: "Tandoori Mix Veg.", price: 10.95 },
  "tandoori-mushroom": { name: "Tandoori Mushroom", price: 10.95 },
  "tandoori-paneer": { name: "Tandoori Paneer", price: 11.95 },
  "chicken-tikka-app": { name: "Chicken Tikka", price: 11.95 },
  "malai-chicken-app": { name: "Malai Chicken", price: 11.95 },
  "achari-chicken-tikka-app": { name: "Achari Chicken Tikka", price: 11.95 },
  "lamb-seekh-kabab-app": { name: "Lamb Seek Kabab", price: 12.95 },
  "lamb-boti-kabab-app": { name: "Lamb Boti Kabab", price: 12.95 },
  "lentil-soup": { name: "Lentil Soup", price: 6.95 },
  "chicken-soup": { name: "Chicken Soup", price: 7.95 },
  "om-green-salad": { name: "Om Green Salad", price: 7.95 },
  "chicken-tikka-masala": { name: "Chicken Tikka Masala", price: 18.95 },
  "butter-chicken": { name: "Butter Chicken", price: 18.95 },
  "chicken-chettinad": { name: "Chicken Chettinad", price: 18.95 },
  "chicken-curry": { name: "Chicken Curry", price: 18.95 },
  "chicken-kadhai": { name: "Chicken Kadhai", price: 18.95 },
  "chicken-korma": { name: "Chicken Korma", price: 18.95 },
  "chicken-saag": { name: "Chicken Saag", price: 18.95 },
  "chicken-tikka-curry": { name: "Chicken Tikka Curry", price: 18.95 },
  "chicken-vindaloo": { name: "Chicken Vindaloo", price: 18.95 },
  "mango-chicken": { name: "Mango Chicken", price: 18.95 },
  "lamb-bhuna": { name: "Lamb Bhuna", price: 20.95 },
  "lamb-chettinad": { name: "Lamb Chettinad", price: 20.95 },
  "lamb-dhansaak": { name: "Lamb Dhansaak", price: 20.95 },
  "lamb-jalfrez": { name: "Lamb Jalfrez", price: 20.95 },
  "lamb-kadai": { name: "Lamb Kadai", price: 20.95 },
  "lamb-korma": { name: "Lamb Korma", price: 20.95 },
  "lamb-rogan-josh": { name: "Lamb Rogan Josh", price: 20.95 },
  "lamb-saag": { name: "Lamb Saag", price: 20.95 },
  "lamb-tikka-masala": { name: "Lamb Tikka Masala", price: 20.95 },
  "lamb-vindaloo": { name: "Lamb Vindaloo", price: 20.95 },
  "goat-bhuna": { name: "Goat Bhuna", price: 23.95 },
  "goat-curry": { name: "Goat Curry", price: 23.95 },
  "goat-kadai": { name: "Goat Kadai", price: 23.95 },
  "goat-vindaloo": { name: "Goat Vindaloo", price: 23.95 },
  "om-daal": { name: "OM Daal", price: 17.95 },
  "om-bhurji": { name: "OM Bhurji", price: 17.95 },
  "paneer-tikka-masala": { name: "Paneer Tikka Masala", price: 17.95 },
  "achari-bainghan": { name: "Achari Bainghan", price: 17.95 },
  "aloo-gobi-matar": { name: "Aloo Gobi Matar", price: 17.95 },
  "bhindi-masala": { name: "Bhindi Masala", price: 17.95 },
  "chana-masala": { name: "Chana Masala", price: 17.95 },
  "chana-saag": { name: "Chana Saag", price: 17.95 },
  "delhi-masala-daal": { name: "Delhi Masala Daal", price: 17.95 },
  "malai-kofta": { name: "Malai Kofta", price: 17.95 },
  "saag-paneer": { name: "Saag Paneer", price: 17.95 },
  "veg-curry": { name: "Veg. Curry", price: 17.95 },
  "vegetable-korma": { name: "Vegetable Korma", price: 17.95 },
  "fish-masala": { name: "Fish Masala", price: 23.95 },
  "goan-salmon-curry": { name: "Goan Salmon Curry", price: 23.95 },
  "goan-shrimp-curry": { name: "Goan Shrimp Curry", price: 23.95 },
  "shrimp-curry": { name: "Shrimp Curry", price: 23.95 },
  "shrimp-korma": { name: "Shrimp Korma", price: 23.95 },
  "shrimp-saag": { name: "Shrimp Saag", price: 23.95 },
  "shrimp-vindaloo": { name: "Shrimp Vindaloo", price: 23.95 },
  "salmon-vindaloo": { name: "Salmon Vindaloo", price: 23.95 },
  "shrimp-tikka-masala": { name: "Shrimp Tikka Masala", price: 23.95 },
  "om-mixed-grill": { name: "OM Mixed Grill", price: 30.95 },
  "achari-chicken-grill": { name: "Achari Chicken", price: 20.95 },
  "malai-kabab": { name: "Malai Kabab", price: 20.95 },
  "tandoori-chicken": { name: "Tandoori Chicken", price: 20.95 },
  "tandoori-chicken-tikka": { name: "Tandoori Chicken Tikka", price: 20.95 },
  "lamb-boti-kebab": { name: "Lamb Boti Kebab", price: 22.95 },
  "lamb-seekh-kebab": { name: "Lamb Seekh Kebab", price: 22.95 },
  "salmon-tikka": { name: "Salmon Tikka", price: 25.95 },
  "tandoori-shrimp": { name: "Tandoori Shrimp", price: 25.95 },
  "plain-naan": { name: "Plain Naan", price: 3.95 },
  "garlic-naan": { name: "Garlic Naan", price: 4.95 },
  "onion-naan": { name: "Onion Naan", price: 4.95 },
  "chicken-tikka-naan": { name: "Chicken Tikka Naan", price: 5.95 },
  "om-bread-sweet": { name: "Om Bread (Sweet)", price: 5.95 },
  "paneer-naan": { name: "Paneer Naan", price: 5.95 },
  "special-3-cheese-naan": { name: "Special 3 Cheese Naan", price: 6.95 },
  "special-chili-garlic-naan": { name: "Special Chili Garlic Naan", price: 6.95 },
  "bread-basket": { name: "Bread Basket", price: 13.95 },
  "plain-roti": { name: "Plain Roti", price: 4.95 },
  "aloo-paratha": { name: "Aloo Paratha", price: 5.95 },
  "laccha-paratha": { name: "Laccha Paratha", price: 5.95 },
  "mint-paratha": { name: "Mint Paratha", price: 5.95 },
  "plain-basmati-rice": { name: "Plain Basmati Rice", price: 3.95 },
  "om-sweet-pulao": { name: "OM Sweet Pulao", price: 7.95 },
  "lemon-rice": { name: "Lemon Rice", price: 7.95 },
  "matar-pulao": { name: "Matar Pulao", price: 7.95 },
  "veg-biryani": { name: "Veg. Biryani", price: 18.95 },
  "chicken-biryani-hyderabadi": { name: "Chicken Biryani Hyderabadi", price: 20.95 },
  "lamb-biryani": { name: "Lamb Biryani", price: 22.95 },
  "goat-biryani": { name: "Goat Biryani", price: 23.95 },
  "shrimp-biryani": { name: "Shrimp Biryani", price: 23.95 },
  "mint-chutney": { name: "Mint Chutney", price: 2.95 },
  "mixed-pickle": { name: "Mixed Pickle", price: 2.95 },
  "onion-relish": { name: "Onion Relish", price: 2.95 },
  "tamarind-chutney": { name: "Tamarind Chutney", price: 2.95 },
  "papadum": { name: "Papadum", price: 3.95 },
  "mango-chutney": { name: "Mango Chutney", price: 4.95 },
  "raita": { name: "Raita", price: 4.95 },
  "jeera-aloo": { name: "Jeera Aloo", price: 9.95 },
  "om-daal-side": { name: "Om Daal", price: 9.95 },
  "delhi-masala-daal-side": { name: "Delhi Masala Daal", price: 9.95 },
  "om-kheer": { name: "OM Kheer", price: 5.95 },
  "gulab-jamun": { name: "Gulab Jamun", price: 6.95 },
  "mango-kulfi": { name: "Mango Kulfi", price: 6.95 },
  "pistachio-kulfi": { name: "Pistachio Kulfi", price: 6.95 },
  "ras-malai": { name: "Ras Malai", price: 6.95 },
  "soft-drinks": { name: "Soft Drinks", price: 2.95 },
  "water": { name: "Water", price: 2.95 },
  "sparkling-water": { name: "Sparkling Water", price: 3.95 },
  "mango-lassi": { name: "Mango Lassi", price: 6.95 },
  "catering-0-0-piece": { name: "Samosas", price: 2.75 },
  "catering-0-1-half": { name: "Onion Bhajia (Half Tray)", price: 65.0 },
  "catering-0-1-full": { name: "Onion Bhajia (Full Tray)", price: 115.0 },
  "catering-0-2-half": { name: "Vegetable Pakora (Half Tray)", price: 65.0 },
  "catering-0-2-full": { name: "Vegetable Pakora (Full Tray)", price: 125.0 },
  "catering-0-3-half": { name: "Sweet & Sour Gobi (Half Tray)", price: 75.0 },
  "catering-0-3-full": { name: "Sweet & Sour Gobi (Full Tray)", price: 145.0 },
  "catering-0-4-half": { name: "Tandoori Mushroom (Half Tray)", price: 65.0 },
  "catering-0-4-full": { name: "Tandoori Mushroom (Full Tray)", price: 150.0 },
  "catering-0-5-half": { name: "Paneer Tikka (Half Tray)", price: 83.0 },
  "catering-0-5-full": { name: "Paneer Tikka (Full Tray)", price: 160.0 },
  "catering-0-6-half": { name: "Tandoori Vegetable (Half Tray)", price: 85.0 },
  "catering-0-6-full": { name: "Tandoori Vegetable (Full Tray)", price: 160.0 },
  "catering-1-0-half": { name: "Tandoori Chicken (Half Tray)", price: 90.0 },
  "catering-1-0-full": { name: "Tandoori Chicken (Full Tray)", price: 170.0 },
  "catering-1-1-half": { name: "Chicken Tikka (Half Tray)", price: 85.0 },
  "catering-1-1-full": { name: "Chicken Tikka (Full Tray)", price: 155.0 },
  "catering-1-2-half": { name: "Achari Chicken Tikka (Half Tray)", price: 85.0 },
  "catering-1-2-full": { name: "Achari Chicken Tikka (Full Tray)", price: 155.0 },
  "catering-1-3-half": { name: "Malai Kebab (Half Tray)", price: 85.0 },
  "catering-1-3-full": { name: "Malai Kebab (Full Tray)", price: 155.0 },
  "catering-1-4-half": { name: "Lamb Seekh Kebab (Half Tray)", price: 95.0 },
  "catering-1-4-full": { name: "Lamb Seekh Kebab (Full Tray)", price: 190.0 },
  "catering-1-5-half": { name: "Salmon Tikka (Half Tray)", price: 150.0 },
  "catering-1-5-full": { name: "Salmon Tikka (Full Tray)", price: 290.0 },
  "catering-1-6-half": { name: "Tandoori Shrimp (Half Tray)", price: 155.0 },
  "catering-1-6-full": { name: "Tandoori Shrimp (Full Tray)", price: 290.0 },
  "catering-2-0-half": { name: "Bhindi Masala (Half Tray)", price: 87.0 },
  "catering-2-0-full": { name: "Bhindi Masala (Full Tray)", price: 169.0 },
  "catering-2-1-half": { name: "Aloo Gobi Matar (Half Tray)", price: 87.0 },
  "catering-2-1-full": { name: "Aloo Gobi Matar (Full Tray)", price: 169.0 },
  "catering-2-2-half": { name: "OM Daal (Half Tray)", price: 87.0 },
  "catering-2-2-full": { name: "OM Daal (Full Tray)", price: 169.0 },
  "catering-2-3-half": { name: "Yellow Daal (Half Tray)", price: 80.0 },
  "catering-2-3-full": { name: "Yellow Daal (Full Tray)", price: 160.0 },
  "catering-2-4-half": { name: "Vegetable Curry (Half Tray)", price: 80.0 },
  "catering-2-4-full": { name: "Vegetable Curry (Full Tray)", price: 160.0 },
  "catering-2-5-half": { name: "Chana Saag (Half Tray)", price: 87.0 },
  "catering-2-5-full": { name: "Chana Saag (Full Tray)", price: 169.0 },
  "catering-2-6-half": { name: "Chana Masala (Half Tray)", price: 87.0 },
  "catering-2-6-full": { name: "Chana Masala (Full Tray)", price: 169.0 },
  "catering-2-7-half": { name: "Vegetable Korma (Half Tray)", price: 87.0 },
  "catering-2-7-full": { name: "Vegetable Korma (Full Tray)", price: 169.0 },
  "catering-2-8-half": { name: "Malai Kofta (Half Tray)", price: 89.0 },
  "catering-2-8-full": { name: "Malai Kofta (Full Tray)", price: 173.0 },
  "catering-2-9-half": { name: "Saag Paneer (Half Tray)", price: 89.0 },
  "catering-2-9-full": { name: "Saag Paneer (Full Tray)", price: 172.0 },
  "catering-2-10-half": { name: "Paneer Tikka Masala (Half Tray)", price: 89.0 },
  "catering-2-10-full": { name: "Paneer Tikka Masala (Full Tray)", price: 172.0 },
  "catering-2-11-half": { name: "Paneer Makhani (Half Tray)", price: 89.0 },
  "catering-2-11-full": { name: "Paneer Makhani (Full Tray)", price: 172.0 },
  "catering-3-0-half": { name: "Butter Chicken (Half Tray)", price: 93.0 },
  "catering-3-0-full": { name: "Butter Chicken (Full Tray)", price: 179.0 },
  "catering-3-1-half": { name: "Chicken Tikka Masala (Half Tray)", price: 93.0 },
  "catering-3-1-full": { name: "Chicken Tikka Masala (Full Tray)", price: 179.0 },
  "catering-3-2-half": { name: "Chicken Saag (Half Tray)", price: 93.0 },
  "catering-3-2-full": { name: "Chicken Saag (Full Tray)", price: 179.0 },
  "catering-3-3-half": { name: "Chicken Korma (Half Tray)", price: 93.0 },
  "catering-3-3-full": { name: "Chicken Korma (Full Tray)", price: 179.0 },
  "catering-3-4-half": { name: "Chicken Vindaloo (Half Tray)", price: 93.0 },
  "catering-3-4-full": { name: "Chicken Vindaloo (Full Tray)", price: 179.0 },
  "catering-3-5-half": { name: "Chicken Do Pyaza (Half Tray)", price: 93.0 },
  "catering-3-5-full": { name: "Chicken Do Pyaza (Full Tray)", price: 179.0 },
  "catering-3-6-half": { name: "Chicken Curry (Half Tray)", price: 93.0 },
  "catering-3-6-full": { name: "Chicken Curry (Full Tray)", price: 179.0 },
  "catering-3-7-half": { name: "Mango Chicken (Half Tray)", price: 93.0 },
  "catering-3-7-full": { name: "Mango Chicken (Full Tray)", price: 179.0 },
  "catering-4-0-half": { name: "Lamb Rogan Josh (Half Tray)", price: 97.0 },
  "catering-4-0-full": { name: "Lamb Rogan Josh (Full Tray)", price: 191.0 },
  "catering-4-1-half": { name: "Lamb Tikka Masala (Half Tray)", price: 97.0 },
  "catering-4-1-full": { name: "Lamb Tikka Masala (Full Tray)", price: 191.0 },
  "catering-4-2-half": { name: "Lamb Korma (Half Tray)", price: 97.0 },
  "catering-4-2-full": { name: "Lamb Korma (Full Tray)", price: 191.0 },
  "catering-4-3-half": { name: "Lamb Vindaloo (Half Tray)", price: 97.0 },
  "catering-4-3-full": { name: "Lamb Vindaloo (Full Tray)", price: 191.0 },
  "catering-4-4-half": { name: "Lamb Chettinad (Half Tray)", price: 97.0 },
  "catering-4-4-full": { name: "Lamb Chettinad (Full Tray)", price: 191.0 },
  "catering-4-5-half": { name: "Lamb Bhuna (Half Tray)", price: 97.0 },
  "catering-4-5-full": { name: "Lamb Bhuna (Full Tray)", price: 191.0 },
  "catering-4-6-half": { name: "Lamb Kadai (Half Tray)", price: 97.0 },
  "catering-4-6-full": { name: "Lamb Kadai (Full Tray)", price: 191.0 },
  "catering-4-7-half": { name: "Lamb Saag (Half Tray)", price: 95.0 },
  "catering-4-7-full": { name: "Lamb Saag (Full Tray)", price: 185.0 },
  "catering-5-0-half": { name: "Goan Salmon Curry (Half Tray)", price: 115.0 },
  "catering-5-0-full": { name: "Goan Salmon Curry (Full Tray)", price: 200.0 },
  "catering-5-1-half": { name: "Fish Masala (Salmon) (Half Tray)", price: 115.0 },
  "catering-5-1-full": { name: "Fish Masala (Salmon) (Full Tray)", price: 200.0 },
  "catering-5-2-half": { name: "Goan Shrimp Curry (Half Tray)", price: 120.0 },
  "catering-5-2-full": { name: "Goan Shrimp Curry (Full Tray)", price: 220.0 },
  "catering-5-3-half": { name: "Shrimp Korma (Half Tray)", price: 120.0 },
  "catering-5-3-full": { name: "Shrimp Korma (Full Tray)", price: 220.0 },
  "catering-5-4-half": { name: "Shrimp Saag (Half Tray)", price: 120.0 },
  "catering-5-4-full": { name: "Shrimp Saag (Full Tray)", price: 220.0 },
  "catering-5-5-half": { name: "Shrimp Tikka Masala (Half Tray)", price: 120.0 },
  "catering-5-5-full": { name: "Shrimp Tikka Masala (Full Tray)", price: 220.0 },
  "catering-5-6-half": { name: "Shrimp Curry (Half Tray)", price: 120.0 },
  "catering-5-6-full": { name: "Shrimp Curry (Full Tray)", price: 220.0 },
  "catering-6-0-half": { name: "Vegetable Biryani (Half Tray)", price: 79.0 },
  "catering-6-0-full": { name: "Vegetable Biryani (Full Tray)", price: 149.0 },
  "catering-6-1-half": { name: "Chicken Biryani (Half Tray)", price: 93.0 },
  "catering-6-1-full": { name: "Chicken Biryani (Full Tray)", price: 179.0 },
  "catering-6-2-half": { name: "Lamb Biryani (Half Tray)", price: 99.0 },
  "catering-6-2-full": { name: "Lamb Biryani (Full Tray)", price: 189.0 },
  "catering-6-3-half": { name: "Goat Biryani (Half Tray)", price: 120.0 },
  "catering-6-3-full": { name: "Goat Biryani (Full Tray)", price: 235.0 },
  "catering-6-4-half": { name: "Shrimp Biryani (Half Tray)", price: 120.0 },
  "catering-6-4-full": { name: "Shrimp Biryani (Full Tray)", price: 235.0 },
  "catering-7-0-piece": { name: "Naan", price: 3.0 },
  "catering-7-1-piece": { name: "Roti", price: 3.0 },
  "catering-7-2-piece": { name: "OM Bread", price: 4.5 },
  "catering-7-3-piece": { name: "Paneer Naan", price: 4.5 },
  "catering-7-4-piece": { name: "Garlic Naan", price: 3.5 },
  "catering-7-5-piece": { name: "Onion Naan", price: 4.5 },
  "catering-7-6-piece": { name: "Lacha Paratha", price: 3.5 },
  "catering-7-7-piece": { name: "Aloo Paratha", price: 4.5 },
  "catering-8-0-half": { name: "Basmati Rice (Half Tray)", price: 40.0 },
  "catering-8-0-full": { name: "Basmati Rice (Full Tray)", price: 75.0 },
  "catering-8-1-half": { name: "OM Sweet Rice (Half Tray)", price: 45.0 },
  "catering-8-1-full": { name: "OM Sweet Rice (Full Tray)", price: 85.0 },
  "catering-8-2-half": { name: "Lemon Rice (Half Tray)", price: 45.0 },
  "catering-8-2-full": { name: "Lemon Rice (Full Tray)", price: 85.0 },
  "catering-8-3-half": { name: "Matar Pulao (Half Tray)", price: 45.0 },
  "catering-8-3-full": { name: "Matar Pulao (Full Tray)", price: 85.0 },
  "catering-8-4-half": { name: "Green Salad (Half Tray)", price: 40.0 },
  "catering-8-4-full": { name: "Green Salad (Full Tray)", price: 75.0 },
  "catering-9-0-piece": { name: "Gulab Jamun", price: 2.25 },
  "catering-9-1-half": { name: "OM Kheer (Half Tray)", price: 60.0 },
  "catering-9-1-full": { name: "OM Kheer (Full Tray)", price: 140.0 },
  "catering-9-2-piece": { name: "Soda", price: 1.99 },
  "catering-9-3-piece": { name: "Mango Lassi", price: 3.95 },
  "om-special": { name: "OM Special", price: 18.95 },
} as const;

export type OrderCatalogItemId = keyof typeof ORDER_ITEM_CATALOG;
